// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvmJwS5hehVfzEZ1ADb6TossZ7reOJIxw',
    appId: '1:147972958822:web:357fbd999bb4fcb3185ba7',
    messagingSenderId: '147972958822',
    projectId: 'keyake-f182e',
    authDomain: 'keyake-f182e.firebaseapp.com',
    storageBucket: 'keyake-f182e.firebasestorage.app',
    measurementId: 'G-NBWW14VGJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEawNuA-vaLFORIMW0OL-wGPkEJ8Nrrpk',
    appId: '1:147972958822:android:5dc5810960bd27be185ba7',
    messagingSenderId: '147972958822',
    projectId: 'keyake-f182e',
    storageBucket: 'keyake-f182e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_TkQDRA2AMBh8tNj5YPZoGIv6RdH7Sjo',
    appId: '1:147972958822:ios:c3b7878057599c99185ba7',
    messagingSenderId: '147972958822',
    projectId: 'keyake-f182e',
    storageBucket: 'keyake-f182e.firebasestorage.app',
    iosBundleId: 'com.example.stackBufferTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_TkQDRA2AMBh8tNj5YPZoGIv6RdH7Sjo',
    appId: '1:147972958822:ios:c3b7878057599c99185ba7',
    messagingSenderId: '147972958822',
    projectId: 'keyake-f182e',
    storageBucket: 'keyake-f182e.firebasestorage.app',
    iosBundleId: 'com.example.stackBufferTestTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2x2CN5HEVIwPC6XpOt_kiby5Aa9LGkgI',
    appId: '1:147972958822:web:abf63e5b3e19244b185ba7',
    messagingSenderId: '147972958822',
    projectId: 'keyake-f182e',
    authDomain: 'keyake-f182e.firebaseapp.com',
    storageBucket: 'keyake-f182e.firebasestorage.app',
    measurementId: 'G-DQLZJF4K9T',
  );
}
